- name: Longhorn setup 
  hosts: Worker_Node
  remote_user: ubuntu 
  tasks:
    - name: install pre-requisites
      shell: |
              sudo apt-get install -y open-iscsi
              sudo apt-get install -y nfs-common
    


