- name: Longhorn on Master_Node
  hosts: Master_Node
  remote_user: ubuntu
  tasks:
    - name: install helm on master Node
      shell: |
              echo 'export VERIFY_CHECKSUM=false' >> /root/.bashrc
              source /root/.bashrc
              curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
              chmod 700 get_helm.sh
              HELM_INSTALL_DIR=/usr/bin ./get_helm.sh

    - name: installing longhorn with helm
      shell: |
              helm repo add longhorn https://charts.longhorn.io
              helm repo update
              helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace
    
