- name: Configure K8s Master Node
  hosts: Master_Node
  remote_user: ubuntu
  roles:
    - role: kubernetes_master

- name: Configure K8s Worker Node
  hosts: Worker_Node
  remote_user: ubuntu
  roles:
    - role: kubernetes_worker
